### ISSUE TITLE
source contains code licensed incompatibly with main license

### ISSUE THREAD

**Issue by jonassmedegaard** [Netatalk/netatalk#1185]
Since git commit f4a579c, this project contains files licensed under SSLeay, which is incompatible with GPL-2+ covering the project generally.

The mere existence of the added files is not a problem in principle, but building code which links with those files renders the whole build impossibly licensed, which is doing your users a disservice.

Please strongly consider to document very clearly which build flags render the built product illegal to redistribute, preferrably not only in instructional README files but also by emitting big fat warnings during build when such a scenario is detected, and ensuring the such a scenario cannot occur by default, only through explicitly enabling some --not-licensed-for-distribution build argument.

**Comment by rdmark** [comment]
Thank you for bringing this to our attention. This was our misunderstanding on how these two licenses interact.

For future reference, the FSF does corroborate that the license is incompatible with the GPL:

> The license of OpenSSL is a conjunction of two licenses, one called “OpenSSL License” and the other being the license of SSLeay. You must follow both. The combination results in a copyleft free software license that is incompatible with the GNU GPL. It also has an advertising clause like the [original BSD license](https://www.gnu.org/licenses/license-list.en.html#OriginalBSD) and the [Apache 1 license](https://www.gnu.org/licenses/license-list.en.html#apache1).

https://www.gnu.org/licenses/license-list.en.html#OpenSSL

**Comment by dgsga** [comment]
Fixed by PR #1186

**Comment by NJRoadfan** [comment]
Netatalk apparently had issues with this before. Likely unanswered questions about linking to OpenSSL: https://groups.google.com/g/comp.sys.apple2/c/WSBqhSNygrg/m/omG4zbg-k-sJ

At least now we know why the DHX2 UAM uses libgcrypt!

**Comment by rdmark** [comment]
This is very enlightening thread, with input from some of the big names in the community. Thanks for sharing. 

I always assumed that DHX and DHX2 used different cryptography under the hood for this reason (dependent on different libraries) but looking at Apple’s [UAM spec](https://developer.apple.com/library/archive/documentation/Networking/Conceptual/AFP/AFPSecurity/AFPSecurity.html#//apple_ref/doc/uid/TP40000854-CH232-SW1) I realize that both are CAST-128 / CBC under he hood…

**Comment by NJRoadfan** [comment]
Does the current official .deb of Netatalk 3.1 ship with the DHCAST128 and randnum UAMs compiled in, or is just DHX2 enabled?

For reference, in the early 2000s, netatalk was distributed with UAMs that required OpenSSL disabled due to licensing (apparently even just dynamically linking to the library was a problem). The original Debian thread can be found here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=191790

The good news is that switching to WolfSSL solves this outside of the missing CAST functions. It looks pretty straight forward to switch that to libgcrypt though. Ideally it would be great to get the rest of the UAMs moved over to libgcrypt, but given the context, debugging it and making sure everything is secure could be a headache.

**Comment by dgsga** [comment]
@NJRoadfan, using nettle (https://github.com/gnutls/nettle) seems to be the way to go. It's very easy to use. So far I have updated DHX cast128 functions and Randnum / afppasswd DES functions to use this low-level cryptographic library so we can leave the whole OpenSSL ecosystem behind us.

**Comment by rdmark** [comment]
The Nettle idea will be worked on in https://github.com/Netatalk/netatalk/issues/1212
