### ISSUE TITLE
Support for ASP/DSI/PAP child process types

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1334]
Netatalk 2.x is able to spawn child processes of different types depending on the transport layer. In 3.x this was simplified to only support DSI/TCP.

https://github.com/Netatalk/netatalk/blob/branch-netatalk-2-4/libatalk/util/server_child.c

**Comment by NJRoadfan** [comment]
Some notes regarding afpd and dsi/atp support

`afp_config.c`
Re-add DSI and ATP specific logic in 'configfree()`
Re-add DSI and ATP specific logic in 'configinit()`. Code here needs to be moved back to `dsi_start()`, which is now in `main.c` (maybe move it back).
The functions `DSIConfigInit()` and `ASPConfigInit()` need to be restored and refactored to support the new INI configuration system since AFPConfigInit() is obsolete in 3.x.
Maybe re-add SLP support and `dsi_cleanup()`?
Re-add `asp_start()` and `asp_cleanup()`.

`main.c`
Child spawning code in `main()` needs to be converted back to being protocol agnostic. `AFPPROTO_DSI` and `AFPPROTO_ATP` variables need to return in volume objects to specific which protocol a volume is set to listen on.

`server_child.c`
The function `server_child_setup()` needs to be re-added, it is used by `asp_getsess.c`.

**Comment by rdmark** [comment]
I knew this was removed as part of the continuous service feature, but imagined that it was a remnant of DSI/ASP server process handling.

We will know for certain soon enough.
