### ISSUE TITLE
2.4: `/etc/ld.so.conf.d/libatalk.conf` installed pointing to `/usr/lib`

### ISSUE THREAD

**Issue by VorpalBlade** [Netatalk/netatalk#1394]
**Describe the bug**
When making a distro package and installing to `/usr/lib` the `/etc/ld.so.conf.d/libatalk.conf` file really isn't needed nor wanted.
That should be dropped. There doesn't seem to be a flag to control that.

Additionally I'm not sure that file even makes sense to begin with, /usr/local/lib is generally in the default search path. Rpath (`$ORIGIN/../lib`?) is possibly a better option anyway.

(Side note: For distros like Guix and NixOS, this would be even worse as they install everything to a unique path and only load the currently active packages into the environment.)

**To Reproduce**
Build a distro package for Linux and install to `/usr`.

**Expected behavior**
There should be a meson flag to not install the `ld.so.conf.d` extension file. Perhaps it should be bundled into `-Dwith-init-hooks=false`?

**Environment**
 - Server OS: Arch Linux
 - Client OS: N/A
 - Netatalk Version 2.4.6

**Logs**
N/A

**Additional context**
N/A

**Comment by rdmark** [comment]
I ran into the same issue while doing Debian packaging last night, actually. This is that lintian has to say about it:

> E: netatalk: package-modifies-ld.so-search-path [etc/ld.so.conf.d/libatalk.conf]
N: 
N:   The package changes the search path for the runtime linker, but is not
N:   part of libc. The offending file is in /etc/ld.so.conf.d.
N:   
N:   It is not okay to install libraries in a different directory and then
N:   modify the run-time link path. Shared libraries should go into /usr/lib.
N:   Alternatively, they can require binaries to set the RPATH to find the
N:   library.
N:   
N:   Without this precaution, conflicting libraries may trigger segmentation
N:   faults for what should have been a conflict in the package manager.
N: 
N:   Please refer to Libraries (Section 10.2) in the Debian Policy Manual for
N:   details.
N: 
N:   Visibility: error
N:   Show-Always: no
N:   Check: files/ld-so

The tactical solution that I would propose is to put this behind the `-Dwith-install-hooks` option, since it's logically grouped with ldconfig.

About the broader question: See https://github.com/Netatalk/netatalk/issues/1379 for the discussion that led to this decision. Interestingly, it is specifically Arch and Fedora that do *not* define `/usr/local/lib` in the default dynamic linker search path, i.e. in their official Docker images.

RPATH is an interesting one, because Debian has another policy "binary-or-shlib-defines-rpath" which discourages its use, which is one reason I didn't make it the global default (while it's the default for Solaris and NetBSD.) You are probably aware of the `-Dwith-rpath` option that allows you to opt in.

Ultimately, my goal is to have a build system that by default works out of the box for end users, but with the customization required by packagers. I'm still not entirely sure what the right set of defaults should be.

**Comment by rdmark** [comment]
@VorpalBlade This is my proposed solution: https://github.com/Netatalk/netatalk/pull/1395

Namely, a new boolean meson setup option `-Dwith-ldsoconf` ... with the default still _true_ since folks who build from scratch on say Fedora would otherwise run into these hard-to-troubleshoot missing shared library errors when using the default `/usr/local` prefix.

What do you think?

**Comment by VorpalBlade** [comment]
Sounds good, as long as it is configurable.

**Comment by rdmark** [comment]
Totally configurable. 👍
