### ISSUE TITLE
The ability to set AppleTalk Zone

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1462]
> [...] Another option I might add in the future is setting a custom AppleTalk zone to register the server in as opposed to the default zone. Netatalk 2.x did this by using a full AppleTalk name for the server name(ex: `MyServer@MyZone`) in `afpd.conf`. This can still be done, but it may override the value of `hostname` over on the IP side if I'm reading the code right.

_Originally posted by @NJRoadfan in https://github.com/Netatalk/netatalk/issues/1442#issuecomment-2342394933_

**Comment by NJRoadfan** [comment]
Addressed in #1468. Note that some additional cleanup of the ASP init code was done. There were cases when issuing a SIGHUP to re-load a configuration that afpd was crashing, particularly if a user inputted an invalid zone in `afp.conf`.

**Comment by rdmark** [comment]
@NJRoadfan Just a side note, we have a little bit of an inconsistent option naming situation now: Enable AppleTalk with `appletalk` but modify its behavior with `ddp address` and `ddp zone` etc. Do you think this is acceptable?

**Comment by NJRoadfan** [comment]
Using just `ddp` doesn't make the option stand out and the average person doesn't know what it means anyway. They do know what AppleTalk is however. Also users may be confused if they need to also set an address or zone since the options have similar names. It should be noted that Netatalk 2.x and 4.x both will disable AppleTalk if a user sets an invalid DDP address or zone.

**Comment by rdmark** [comment]
Right, I agree with these points. So one naming scheme option that uses the more well-known term would be:

```
appletalk
appletalk address
appletalk zone
```

etc.
