### ISSUE TITLE
Netatalk randomly selects between WolfSSL or OpenSSL without a meson option to override it

### ISSUE THREAD

**Issue by VorpalBlade** [Netatalk/netatalk#1504]
**Describe the bug**
It seems there is no Meson option to select between WolfSSL or OpenSSL in Netatalk2. This causes issues when packaging since I can't correctly declare the Arch Linux AUR package dependencies (by default these builds are NOT run sandboxed, and will thus pick up whatever package the user have installed). This also makes the distro package non-reproducible.

**To Reproduce**
Build in an environment where WolfSSL is installed, WolfSSL automatically gets used from the system. There is no flag to force use of either WolfSSL or OpenSSL.

**Expected behavior**
A flag to configure which SSL backend to use, to facilatate Linux package building

**Environment**
 - Server OS: Arch Linux
 - Client OS N/A
 - Netatalk Version 2.4.9

**Logs**
Attach syslogs from the malfunctioning process, `maxdebug` log level

**Additional context**
If it is a crash, please attach a [stacktrace](https://github.com/Netatalk/netatalk/wiki/Using-GDB-to-Analyze-a-Crash).

**Comment by rdmark** [comment]
This might be a little counter-intuitive, but netatalk 2.4 (and 3.2) require *both* wolfSSL and OpenSSL for DHX. We use primarily wolfSSL, but CAST symbols are supplied by OpenSSL (or LibreSSL). It's not a great setup, but it's the best we could come up with at the time.

What you _can_ control, is to ignore the system's shared wolfSSL library and force linking with the bundled wolfSSL library that we ship with netatalk. (`-Dwith-ssl-override`)

Arch is an unusual case because it distributes a wolfSSL package that nominally has the capability flags that we look for, but the actual shared library is missing symbols that netatalk requires. I've been tracking this issue in https://github.com/Netatalk/netatalk/issues/1354 ...

**Comment by rdmark** [comment]
Is the above answer adequate, or are you still arguing that there's a bug here? I'm open to new perspectives. :)

**Comment by VorpalBlade** [comment]
Oh sorry, forgot about this. Yeah I was under a misunderstanding about how the different flags related to each other.

In my defense, most programs don't depend on multiple crypto libraries at once, so it seemed reasonable to assume an either-or situation.

**Comment by rdmark** [comment]
No worries. It is a weird setup that came out of an incorrect assumption and subsequent crisis.

As you may have seen, the soon-to-be-released Netatalk 4.0 will use Libgcrypt for everything instead of this hodgepodge. So look forward to packaging that. ;)
