### ISSUE TITLE
Build fails with undeclared 'sparql' variable when building with -Dwith-spotlight=false.

### ISSUE THREAD

**Issue by APCCV** [Netatalk/netatalk#1715]
**Describe the bug**
When building with the spotlight feature off, meson.build fails due to an undeclared 'sparql' variable.

**To Reproduce**
Build with option set to false.

**Expected behavior**
Build should succeed and complete without spotlight.

**Environment**
 - Server OS: Ubuntu 24.04LTS derivative cross compiling for all supported OpenWrt platforms
 - Client OS: Not applicable, issue is at build
 - Netatalk Version: 4.0.3

**Logs**
I already patched the issue so it will take effort to get the log. Build fails when `sparql` is undefined.

**Additional context**
Problem has to do with `endif` tag in `meson.build`. `have_spotlight` condition should be moved into the `if` for spotlight requested.
Solved temporarily with this patch:

```
--- a/meson.build
+++ b/meson.build
@@ -899,15 +899,16 @@ else
             endif
         endif
     endif
+
+    have_spotlight = (
+        sparql.found()
+        and indexer_found
+        and talloc.found()
+        and flex.found()
+        and bison.found()
+    )
 endif

-have_spotlight = (
-    sparql.found()
-    and indexer_found
-    and talloc.found()
-    and flex.found()
-    and bison.found()
-)
 if have_spotlight
     cdata.set('WITH_SPOTLIGHT', 1)
 endif
```

**Comment by rdmark** [comment]
Thanks for reporting! It is way too easy to forget to define variables in the scope that you want to use them in Meson. Did you check that the other four variables are available in the new scope in all situations?

Anyhow, since you have a proposed patch lined up, why don't you file a PR with us? That'll give you automatic credits in the release notes as well. :)
