### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [Netatalk/netatalk#319]
Dear @Netatalk team,

Thanks for your new development but the migration to GitHub is not complete!

There are always (you can export):
- http://netatalk.sourceforge.net/wiki/
- https://sourceforge.net/p/netatalk/code/
- https://sourceforge.net/p/netatalk/_list/tickets
- https://sourceforge.net/p/netatalk/bugs/
- https://sourceforge.net/p/netatalk/feature-requests/
- https://sourceforge.net/p/netatalk/patches/

It can be updated:
- https://sourceforge.net/projects/netatalk/support

I think that you can change the website to: https://github.com/Netatalk/netatalk

You can look here, for example:
- Summary: https://sourceforge.net/projects/handbrake/
- Link on this page: https://sourceforge.net/projects/handbrake/support

No problem for Mailinglists and I think that it is needed to do announcements here:
- netatalk-announce

And you can publish the website on GitHub too.

**Comment by rdmark** [comment]
Thanks for the suggestions!

>There are always (you can export):
> - http://netatalk.sourceforge.net/wiki/

The SF wiki has been down for years. But myself and others have been migrating select content over to the github wiki. No action needed here I think?

> - https://sourceforge.net/p/netatalk/code/

The SF code was simply a clone of the github repo. However it was out of sync ever since we change the name of the main branch to `main`. So I removed the Code section from SF now.

FWIW there is also an out-of-sync netatalk mirror on Gitlab https://gitlab.com/netatalk-team/netatalk

> - https://sourceforge.net/p/netatalk/_list/tickets
> - https://sourceforge.net/p/netatalk/bugs/
> - https://sourceforge.net/p/netatalk/feature-requests/
> - https://sourceforge.net/p/netatalk/patches/

I made the ticket trackers read only (for new tickets) earlier this year. There are still some valid bugs in that tracker. I've been going through them and testing one by one the last few months. I plan to wait until June or so to see if we get feedback from the original reporters. And then take action to migrate any valid, reproducible bugs over, before the end of 2023.

> It can be updated:
> - https://sourceforge.net/projects/netatalk/support

I updated this to point to the github issue tracker.

> I think that you can change the website to: https://github.com/Netatalk/netatalk

I'm not sure I agree with this. The netatalk.sf.net is still the better portal I think, maintaining a modicum of independence from github with links to a broader set of resources.

> You can look here, for example:
> - Summary: https://sourceforge.net/projects/handbrake/
> - Link on this page: https://sourceforge.net/projects/handbrake/support

I think we have covered everything that this project does. But please let me know if there's something I'm missing.

> No problem for Mailinglists and I think that it is needed to do announcements here:
> - netatalk-announce

Actually, the netatalk-announce ML was shut down years ago. We use the netatalk-admins ML for announcement these days.

> And you can publish the website on GitHub too.

So the netatalk website is using PHP which GitHub Pages does not support. It should be trivial to rewrite it to be Pages compatible I guess, but I'm not really motivated to do it myself. If you want to contribute, please don't hesitate to write a fancy new Pages compatible netatalk website. ;)

FYI (most of) the website code is here https://github.com/Netatalk/netatalk-web

**Comment by rdmark** [comment]
Found two more links to the dead wiki, in the Wiki and External Links navbar items. I removed both items altogether. 

For now, this is an appropriate state for the github migration I think. The sourceforge project is still valuable to keep around for the historical release archive, the mailing lists, and the read-only bug tracker.

The website migration is a bigger topic for another day and another ticket, I think.
