### ISSUE TITLE
Build on macos in github workflow

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#321]
To set up a job to build on macos in the github workflow. Similarly to: https://github.com/dgsga/netatalk/blob/macos/.github/workflows/macos.yml

**Comment by rdmark** [comment]
@dgsga Do you have a general idea of the bare minimum needed to set this up?

I saw your massive commit setting up the meson build system, but is this really required for the github workflow? https://github.com/dgsga/netatalk/commit/3e336a1ea3c562f7b8c14fde43bf5b112cd52fde

**Comment by dgsga** [comment]
@rdmark, please see latest PR. The only reason I created a meson build system for my branch is that it builds netatalk in 6 seconds rather than 55 for an auto tools build. It's an amazing build system but I'm unsure of compatibility. Their website [https://mesonbuild.com](url) says 'multiplatform support for Linux, macOS, Windows, GCC, Clang, Visual Studio and others'...
