### ISSUE TITLE
[2.2] Add support for macOS hosts

### ISSUE THREAD

**Issue by dgsga** [Netatalk/netatalk#350]
The 2.2 branch can be compiled on MacOS with branch-specific patches along with changes ported from upstream main

**Comment by barracuda156** [comment]
@dgsga Fails with clang for us: https://github.com/macports/macports-ports/pull/18240#issuecomment-1502396330
gcc build is fine.

Do you know what specifically has to be backported to address this?

**Comment by dgsga** [comment]
A PR is being prepared to address these issues.

**Comment by rdmark** [comment]
PR #349 has been merged now.

**Comment by barracuda156** [comment]
> For future reference: commit [36fd5c6](https://github.com/Netatalk/netatalk/pull/349/commits/36fd5c6e3b6be14343473673c957a559c01c1d9c) removed the old OSX Server implementation of Apple netat. If someone attempts to implement a new appletalk stack on macOS this may serve as reference. (nudge nudge @rofore )

@rdmark @dgsga By the way was it broken? Because on older macOS it was building fine with it. Only [some] newer systems failed (or possibly due to Clang being used by default there).

**Comment by rdmark** [comment]
@barracuda156 Please see the discussion in the PR that I linked to.

IMHO the main problem with the MACOSX_SERVER conditional was that it de-facto assumed any macOS version was OSX Server, so a few of the branches led to code that worked around long since resolved limitations in OSX, as well as expect the netat headers to exist (which were removed with 10.6).

All that to say, these changes were made to allow netatalk to build on the very latest macOS versions. We are deliberately removing support for old OSX versions. If you want to run netatalk on OSX Server, please use a contemporaneous release version. :)

**Comment by barracuda156** [comment]
@rdmark 

> We are deliberately removing support for old OSX versions

Hmm, maybe make it conditional? People use macOS on PPC.

**Comment by rdmark** [comment]
> @rdmark
> 
> > We are deliberately removing support for old OSX versions
> 
> Hmm, maybe make it conditional? People use macOS on PPC.

Please note that the platform specific code hidden behind conditionals is a very small part. A platform also needs to support a recent enough toolchain, including the C compiler, autotools, cryptography libs like OpenSSL, etc. Take OpenSSL for instance: We only support v1.1 or later, not the old insecure 1.0. APIs change over time and we often break compatibility with old libraries as a necessity.

Anyhow, before getting deeper into a theoretical debate, perhaps you can propose a particular legacy OSX version that you think is important to support, and then we can investigate / test how feasible it would be to make it work? The one that springs to mind to me is Sorbet Leopard, the retooled version of 10.5. Step one would probably be to get MacPorts up and running and try to install the requisite toolchain for netatalk and see how far you get.

**Comment by barracuda156** [comment]
@rdmark Thank you for responding on this.

> Please note that the platform specific code hidden behind conditionals is a very small part. A platform also needs to support a recent enough toolchain, including the C compiler, autotools, cryptography libs like OpenSSL, etc. Take OpenSSL for instance: We only support v1.1 or later, not the old insecure 1.0. APIs change over time and we often break compatibility with old libraries as a necessity.

The latest GCC and the latest OpenSSL build and work on MacOS starting from at least 10.5.8 (that is, ppc/ppc64 included). (Likely on Tiger as well, though I have not tested GCC above 7.5.0 there.) There is no problem here whatsoever.

> Anyhow, before getting deeper into a theoretical debate, perhaps you can propose a particular legacy OSX version that you think is important to support, and then we can investigate / test how feasible it would be to make it work? The one that springs to mind to me is Sorbet Leopard, the retooled version of 10.5.

10.5.8 and 10.6 would be awesome to have supported. (“Sorbet Leopard” is identical to `10.5.8 in terms of SDK; folks from Macrumors have updated something like security certs and wallpapers. 10.6 exists for PowerPC, though as an early version, with SDK being somewhat closer to 10.5.8 – I can give details if needed, since that is my main testing OS.)

> Step one would probably be to get MacPorts up and running and try to install the requisite toolchain for netatalk and see how far you get.

I am supporting a large chunk of ports for PowerPC systems :)
Above I have referred my PR with `netatalk` update: the port was abandoned for ages: https://github.com/macports/macports-ports/pull/18240 (CI fail there on the latest macOS, that is why I brought that up here, but on 10.6 it builds fine with GCC).

**Comment by barracuda156** [comment]
@rdmark I recall there was some interest expressed on Macrumors to have `netatalk` working on PPC. I think that is why I made a point to fix it, which did not work initially. Also, as a general policy, we rather have a build working for all supported by Macports systems (as long as it is practically feasible).

**Comment by rdmark** [comment]
Fair enough! If you need further support from this project, don't hesitate to file a new issue ticket and we can take it from there.
