### ISSUE TITLE
nbplkup: displaying special characters in Netatalk 2.2.9

### ISSUE THREAD

**Issue by mactjaap** [Netatalk/netatalk#360]
I was wondering if it is possible to fix the displaying of special characters in the output of nbplkup. I have a AsantéTalk LocalTalk bridge and it is always displayed as: Asant▒Talk . I should be of course AsantéTalk.

See my output:
`AsantéTalk 940863E7:Asant▒Talk                         65476.111:252`

**Comment by rdmark** [comment]
The charset encoding of the service name string is clearly different than what your terminal is using there.

As an experiment I hacked afpd to register the AFP service with a string containing the same accented e. Of course, this is Unicode end to end since that's what the OS is using for both code and terminal, but at least it demonstrates that there's no inherent limitation to the handling of character encoding in nbplkup itself.

```
$ nbplkup
                         rasp32:AFPSérver                         65280.1:128
```

Have you played around with nbplkup's charset options already? There's one command line parameter and two environment variables.

https://netatalk.sourceforge.io/2.2/htmldocs/nbp.1.html

This manual page talks about the supported charsets.

https://netatalk.sourceforge.io/2.2/htmldocs/configuration.html#charsets

For instance, to force the MAC_ROMAN charset do `nbplkup -m MAC_ROMAN`

**Comment by mactjaap** [comment]
Thans for your help! It is no an important problem...but a little bit annoying. 

So I tried your suggestions (even all) but no luck. I tried all the possibilities:

nbplkup -m MAC_CENTRALEUR
nbplkup -m MAC_CHINESE_SIMP
nbplkup -m MAC_CHINESE_TRAD
nbplkup -m MAC_CYRILLIC
nbplkup -m MAC_GREEK
nbplkup -m MAC_HEBREW
nbplkup -m MAC_JAPANESE
nbplkup -m MAC_KOREAN
nbplkup -m MAC_ROMAN
nbplkup -m MAC_TURKISH

Their was definitely something happening with the first part, but the part after the double colon didn't change.

**Comment by mactjaap** [comment]
export ATALK_MAC_CHARSET="MAC_ROMAN"
export ATALK_UNIX_CHARSET="UTF-8"

Doesn't help also.

**Comment by mactjaap** [comment]
I have the idea that the unknown character is also not valid. Also with other tools I don't know what it is.

**Comment by mactjaap** [comment]
Best I could get is: \uFFFD

"Used to replace an incoming character whose value is unknown or unrepresentable in Unicodecompare the use of U+001A as a control character to indicate the substitute function"


Comments	used to replace an incoming character whose value is unknown or unrepresentable in Unicode
compare the use of [U+001A](https://www.fileformat.info/info/unicode/char/001a/index.htm) as a control character to indicate the substitute function

**Comment by rdmark** [comment]
Closing this since all points to the Asante device using an unsupported encoding for the string

**Comment by mactjaap** [comment]
Ok... found a workaround. If you look at the problem the problematic character between Asant and Talk is the byte with the hexadecimal value 8E.


```
00000010  c3 a9 54 61 6c 6b 20 39  34 30 38 36 33 45 37 3a  |..Talk 940863E7:|
00000020  41 73 61 6e 74 8e 54 61  6c 6b 20 20 20 20 20 20  |Asant. Talk      |
```

So my workaround is this since 8E in hexadecimal is 216 in octal.

`nbplkup | sed 's/Asant\o216Talk/AsantéTalk/g'`
