### ISSUE TITLE
netatalk2: World writable spool directory

### ISSUE THREAD

**Issue by VorpalBlade** [Netatalk/netatalk#406]
Arch Linux has a package linting tool ([namcap](https://man.archlinux.org/man/namcap.1)) which I ran on the package I'm creating for Arch Linux AUR. Normally these are packaging issues, but I believe I found some upstream issues as well. This is one of those:

```
netatalk2 W: Directory (var/spool/netatalk) is empty
netatalk2 W: File (var/spool/netatalk) has the world writable bit set.
```

This probably isn't intentional? Especially not the world writable bit. Note, I use `--localstatedir=/var`

**Comment by rdmark** [comment]
The var/spool/netatalk dir is used for papd printer spooling via CUPS, so it being empty upon installation is a non-issue I think. We just need a location to spool temporary files to when a printer queue is active.

The appropriate permissions depends on our implementation of the CUPS backend so a bit of investigation would be needed to make sure our code doesn't currently rely on 777. Interestingly, I read [this guide](https://wiki.alienbase.nl/doku.php?id=slackware:cups) on writing a new CUPS backend, and they use 1777 permissions on their backend's spool dir, but the usecase is different from ours. (more of a drop box for system users to pick up spooled files from)

BTW, the spool dir location is controlled with `--with-spooldir=PATH`

**Comment by rdmark** [comment]
@NJRoadfan As our resident papd expert: Do you have any insights into how the netatalk CUPS backend spooling is designed at the moment?

**Comment by NJRoadfan** [comment]
Right now papd writes the packets received from a client print job to /var/spool/netatalk (it likely varies per OS). Once the job has been completely transferred, it is forwarded to either CUPS or lpd and the spool file is deleted. This code is old and hasn't been touched in a long time, mostly because it works. Any old netatalk 2.x packages out there likely have this set with no ill effect.

I wonder how Samba does it these days. I would be hesitant to trust that documentation though as it is likely very obsolete. A lot changed with CUPS from 1.6 onwards. At least that example uses the sticky bit (1777) that only allows the creator of the file to modify/delete their own files.

**Comment by rdmark** [comment]
Let me close this with no action for now. Please let us know if you disagree with the resolution!
