### ISSUE TITLE
Cannot install on bookworm

### ISSUE THREAD

**Issue by beetlegigg** [Netatalk/netatalk#553]
On Debian Bookworm I cannot - sudo apt install netatalk - the message is:

Package netatalk is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'netatalk' has no installation candidate

It was installing OK on Debian Bullseye.  Can this be fixed?  Thanks.

**Comment by rdmark** [comment]
The netatalk package was removed from Debian 12 (Bookworm) because the package had no maintainer last year.

I took over as maintainer of the Debian package earlier this year, so there's a good chance we can get it added back in Debian 13 (Trixie)... in about 1.5 years.

There is a maintained netatalk package in Debian Unstable (Sid) so as a workaround you can add the Unstable repos to your apt sources:

https://www.addictivetips.com/ubuntu-linux-tips/how-to-run-unstable-packages-on-debian-stable/

You may run into dependency challenges. When I tried this a few months ago I found that I had to pin the `libgcrypt20` library to the unstable version as well. I don't know if Debian 12's repos has gotten an update to their libgcrypt20 package yet or not...

**Comment by rdmark** [comment]
Good to hear that it worked out for you!
