### ISSUE TITLE
File folder Inconsistencies 

### ISSUE THREAD

**Issue by ifoundastick** [Netatalk/netatalk#649]
Hi, 

I'm running a server that hosts 100,000 + files in one directory and we are seeing inconsistencies when doing an ls on a mac or looking at it in finder. If we look at it via windows or linux the files are all there. I wanted to see if there's a limit on number of files per folder netatalk can handle. 
  I've seen this behavor before with smb and theres a flag that you need to add for this but wanted to see if this would be the same. 

Specs for fileserver
CentOS Linux release 7.9.2009 (Core)
netatalk-3.1.12-5.el7.x86_64

**Comment by rdmark** [comment]
@ifoundastick Are you seeing any pattern in what particular files are the source of the inconsistency? Netatalk has some fine-grained settings controlling illegal files, e.g. dot files. This could be one potential cause.

We don't have anything like the Samba option that you mentioned. The only one option in Netatalk that springs to mind is `dircachesize` which you could try increasing and see if it makes a difference. At the very least you should gain some performance to the cost of memory.

All runtime options are documented here: https://netatalk.sourceforge.io/3.1/htmldocs/afp.conf.5.html

I believe the max number of files supported by Netatalk is ~4 billion (same as the HFS+ limit). Due to the architecture of the CNID backend, each file ID is not reusable so you can theoretically exhaust the pool of IDs in extreme cases. Any chance you had 4 billion files created during the lifetime of your shared volume?

See also: https://netatalk.sourceforge.io/3.1/htmldocs/configuration.html#CNID-backends

While on the topic of CNID backends: which particular backend are you using? The default is `bdb` so I assume this one. The `mysql` backend has been reported as more reliable for very large deployments, but with the drawback of having to run a mysql database.

As a final note, I can see that you run an old version of netatalk: 3.1.12. Upgrading to 3.1.18 is recommended. We fixed a large number of security issues.

**Comment by rdmark** [comment]
@ifoundastick Did you have a chance to consider my suggestions above? Anecdotally the `bdb` CNID backend has proven somewhat unreliable at scale, so you may want to consider migrating to the `mysql` backend.

**Comment by ifoundastick** [comment]
I haven't been able to do a maintenance window on this yet. Its running the default dbd backend. Let me get some time to update and see if that helps.

**Comment by rdmark** [comment]
Let me close this for now since there is nothing actionable here right now. Please don't hesitate to reopen with test results, logs, reproduction steps, etc.
