### ISSUE TITLE
[3.2] Roadmap - Add meson build system

### ISSUE THREAD

**Issue by dgsga** [Netatalk/netatalk#707]
@rdmark, I'm on the home straight with creating a meson build system for upstream main (please see dgsga-meson-build branch). I have a few more macros to implement (such as dtrace support) but otherwise all is done. What are your thoughts about how to introduce this? Projects such as dbus had the two build systems running alongside one another for a while before transitioning fully to meson, and users were given an autotools deprecation warning beforehand. 

Just to re-iterate:
Benefits of meson:
It's fast!
Used by well-established open source projects such as qemu, mesa, freedesktop.org (eg dbus), Gnome, glib
The meson.build files have a transparent logic and are easy to update
The dependency search function works really well cross-platform so less user intervention with configure options is required

Let me know what you think...

**Comment by rdmark** [comment]
@dgsga in your mind are there any notable drawbacks with meson?

Off the top of my head, we have three kinds of customers of the build system: enterprise sysadmins, hobby users, and package managers. What I suggest we do is to break down their needs and try to anticipate potential stumbling blocks. 

Having both build systems in parallel for a transitional period sounds like the less drastic approach… do you think it can be done in our project fairly cleanly?

Also, have you looked at what cross platform support look like? Solaris, illumos, the BSDs, Alpine Linux, etc.

**Comment by dgsga** [comment]
On the first point I agree 100%.. On the second, none that I can tell yet. It is being very actively maintained, and any issues arising are addressed promptly. Meson can produce a release package for distribution in the same way as autotools. The only drawback could be cross-platform support which I will test once all the macros have been implemented. The meson build system makes no changes whatsoever to the existing codebase so it can be cleanly implemented.

**Comment by gjcarter2** [comment]
> @rdmark, I'm on the home straight with creating a meson build system for upstream main (please see dgsga-meson-build branch). I have a few more macros to implement (such as dtrace support) but otherwise all is done. What are your thoughts about how to introduce this? Projects such as dbus had the two build systems running alongside one another for a while before transitioning fully to meson, and users were given an autotools deprecation warning beforehand.
> 
> Just to re-iterate: Benefits of meson: It's fast! Used by well-established open source projects such as qemu, mesa, freedesktop.org (eg dbus), Gnome, glib The meson.build files have a transparent logic and are easy to update The dependency search function works really well cross-platform so less user intervention with configure options is required
> 
> Let me know what you think...

I dunno.

The GNU tool chain runs on any platform and meson doesn't, or at least I don't know of a platform that GNU auto tools hasn't been ported too.

Sorta seems like busy work.

Sorta like the conversation I had with some Rust friends of mine because they couldn't convince me to switch.  Yes, C itself is not as safe, but C programmers don't operate in a bubble, we got all sorts of automation and tools to bear that makes our code as safe as Rust if they are automagically included.  No need to reinvent the wheel with a new language and throw away half a century of skill sets in the industry on a new language.

I mean it just seems extreme to me.

**Comment by rdmark** [comment]
@gjcarter2 Thanks for sharing your perspective. I agree that jumping on the latest tech trend bandwagon just because it's new and shiny is a bad idea. At the same time, you shouldn't be afraid of change if brings you long term benefits.

Personally, I'm excited to use Meson because it's super fast and easy to extend. It will make it so much breezier to work in this codebase. I've wasted countless hours waiting for autoconf and automake to do their thing over and over. Also, the rigidness and obscurity of autotools syntax has been a huge time sink whenever we want to make changes to the build system, and in some cases we've had to give up on an idea (e.g. dynamic substitution in generated documentation) because of it.

Meson is ported to all platforms that this project cares about: Linux, the *BSDs, macOS, Illumos, Solaris. Fun fact: Solaris v11 got Meson support in 2020:

https://www.phoronix.com/news/Oracle-Solaris-11.4-SRU19

**Comment by rdmark** [comment]
@dgsga anything left to do here now when https://github.com/Netatalk/netatalk/pull/750 has been merged?

**Comment by rdmark** [comment]
It is timely to be to doing this project. The recently publicized xz backdoor exploited autotools with a malicious m4 macro and bootstrapped tarball practices. Over at the debian-devel mailing list, the idea of encouraging upstream projects to move to Cmake or Meson was floated.

The thread starts at https://lists.debian.org/debian-devel/2024/03/msg00333.html

**Comment by gjcarter2** [comment]
Well, all build systems and of course the software that empowers them have
issues. I hope the decision is based on sound technical or engineering
advantages and not hystery over yet another security issue with a piece of
software.

**Comment by rdmark** [comment]
I agree that all choices of software involve tradeoffs. There is no perfect option. I don't think autotools is going away, but there is surely going to be more scrutiny on projects that use this build system moving forward. 

The big weakness with autotools/autoconf in my opinion, is that it generates something like 50,000 lines of dense m4 macro / shell script code (plus 20,000+ lines of Makefile code) when you bootstrap netatalk. Plus, even the human written m4 macros are obscure and hard for a human to grok. By tradition the generated code is often not revision controlled, but shipped in the bootstrapped release tarballs through a non-transparent process. This was the blind spot that allowed the xz backdoor to get into Debian and Fedora unstable distributions. We have been using the same process in netatalk.

It's definitely possible to distribute autotools build systems more securely, but it introduces overheads one way or another. We either commit all generated code to revision control, which adds a ton of noise to the commit history, as well as labor to maintain. Or, you stop shipping bootstrapped tarballs and mandate that all users supply their own compatible autotools, which is not always feasible in non-GNU operating systems. There may be other approaches that I overlooked.

Meson build configurations in comparison has succinct syntax and no intermediate steps of generated code. This aligns with one of the original goals of this transition which was "The meson.build files have a transparent logic and are easy to update".

**Comment by dgsga** [comment]
> @dgsga anything left to do here now when #750 has been merged?

There will no doubt be some snagging issues which become apparent through use but the implementation is feature-complete.

**Comment by gjcarter2** [comment]
People using their trusted positions to subvert, destroy is on your local
Daily News Website on a daily basis.

https://www.youtube.com/watch?v=SFEewD4EVwU
