### ISSUE TITLE
[2.3] dockerization with CUPS

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#712]
Edit: Original Dockerfile and entry script by Eric Harmon, modified to run all appletalk daemons in addition to afpd.

Original summary:

A cups client can communicate with a cupsd backend over TCP/IP. It would be handy if papd could do the same.

This describes one example with cups-client: https://github.com/olbat/dockerfiles/blob/master/cupsd/README.md

The immediate usecase is for running netatalk services in a docker container. Rather than trying to bundle cups proper in the same container, it is more docker-esque to separate them. To make a clean separation, connective over IP via the docker sockets is required.

**Comment by rdmark** [comment]
@NJRoadfan Off the top of your head, would you say this is feasible?

**Comment by NJRoadfan** [comment]
Not feasible. The CUPS API needs a locally accessible scheduler inside the container in order to create temporary queues for DNS-SD discovered printers. This is for security reasons. See this thread post and Michael's response: https://github.com/OpenPrinting/cups/issues/57#issuecomment-737124995

The "official" containerization of CUPS uses Snap, which doesn't have this problem: https://github.com/OpenPrinting/cups-snap

Down the road with CUPS 3.0 adds the further challenge that we'll need a solution to convert Postscript print jobs to PDF. That would require something like `libcupsfilters` and its many dependencies as part of the container.

**Comment by rdmark** [comment]
Thanks for sharing your insights. I read in the news that Canonical is pushing a strategy of Snap as a cross-platform containerization solution, but I don't think we're quite there yet.

I was able to get to a working state with the monolithic container: https://github.com/Netatalk/netatalk/pull/704

You still have the step of adding and configuring your CUPS printers with the web UI, but it's close to plug'n'play now, and does not rely on CUPS existing on the host.

**Comment by rdmark** [comment]
PR merged.

**Comment by NJRoadfan** [comment]
If using modern driverless printers, they should "just work". No configuration needed in the web interface.
