### ISSUE TITLE
dsi_stream_read: len:0, unexpected EOF

### ISSUE THREAD

**Issue by slowfranklin** [Netatalk/Netatalk#82]
Due to a bug in the handling of extended attributes, certain xattr related operations could result in a broken connection. An application that seems to trigger is reliably is Photos.app.

Patch to follow...

**Comment by hat001** [comment]
commited.

**Comment by sertal70** [comment]
Hi, I'm running in this issue since I upgraded my ubuntu to `19.04` which bringed in the `v3.1.12` of netatalk:
```shell
Oct  1 10:37:01 mediacenter afpd[1408]: Login by sergio (AFP3.4)
Oct  1 10:37:01 mediacenter afpd[1408]: AFP logout by sergio
Oct  1 10:37:01 mediacenter afpd[1408]: dsi_stream_read: len:0, unexpected EOF
Oct  1 10:37:01 mediacenter afpd[1408]: afp_over_dsi: client logged out, terminating DSI session
Oct  1 10:37:01 mediacenter afpd[1408]: AFP statistics: 0.60 KB read, 0.44 KB written
Oct  1 10:38:02 mediacenter afpd[1427]: Login by sergio (AFP3.4)
Oct  1 10:38:02 mediacenter afpd[1427]: AFP logout by sergio
Oct  1 10:38:02 mediacenter afpd[1427]: dsi_stream_read: len:0, unexpected EOF
Oct  1 10:38:02 mediacenter afpd[1427]: afp_over_dsi: client logged out, terminating DSI session
Oct  1 10:38:02 mediacenter afpd[1427]: AFP statistics: 0.60 KB read, 0.44 KB written
```

Before that I was running ubuntu `18.04` with netatalk `v2.2.6-1` and everything were fine.

As workaround I downgraded by adding cosmic repository to ubuntu apt source list and forcing installation of previous package version via apt preferences. Not ideal but it works for the moment.

Please have a look at it, if I can help in any way let me know.

**Comment by ledestin** [comment]
The upgrade 2.2.5 -> 3.1.12 (Debian Stretch -> Buster) caused this for me. The real cause was that afpd runs as `afpd -d -F /etc/netatalk/afp.conf`, i.e. it uses `afp.conf`, and not `afpd.conf`. Thus, the old v2 config isn't used, and there are no shares. After setting up `afp.conf`, my Time Machine backups are back to normal.

**Comment by rmartinsjr** [comment]
Hi @ledestin !

I'm having the same problem with Buster. Configured afp.conf and my shares are working fine, but no Time Machine backups.

Here are my configurations for both Avahi and Netatalk. Can you see any problem on them?

```
<service-group>

  <name replace-wildcards="yes">%h</name>

  <service>
    <type>_afpovertcp._tcp</type>
    <port>548</port>
  </service>

  <service>
    <type>_device-info._tcp</type>
    <port>0</port>
    <txt-record>model=Macmini</txt-record>
  </service>

  <service>
    <type>_adisk._tcp</type>
    <txt-record>sys=waMa=0,adVF=0x100</txt-record>
    <txt-record>dk0=adVN=Time Machine,adVF=0xa1</txt-record>
  </service>
</service-group>
```

```
[Global]
; Global server settings

[Homes]
basedir regex = /home
home name = $u

[Time Machine]
path = "/fileserver/volumes/Time Machine/Time Machine"
vol size limit = 500000
valid users = @timemachine
time machine = yes
```

**Comment by rmartinsjr** [comment]
I realized that Netatalk was also trying to set information on Avahi so I removed the service definition in Avahi and limited "Time Machine" share to:

```
[Time Machine]
path = /fileserver/volumes/Time Machine/Time Machine
time machine = yes
```

And it's working!
